### ISSUE TITLE
HASS: SSL handshake failure 202505

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1207]
Occurred while experimenting https://github.com/kinu-garage/hut_10sqft/issues/1204#issuecomment-2904906038, which makes it harder to identify the trigger.

# Issue
HASS client (Lovelace? I'm unsure) shows an error.

Mac app says:
```
An SSL erro r has occured and a securre connection to the server cannot be made
NSURLError Domain -1200
```

- Android app incl. the one on ChromeOS (brya)
- Mac app

**Comment by 130s** [comment]
I `docker rmi`-ed both Docker images and re-pulled them. Result is the same.
```
$ docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.CreatedAt}}\t{{.Size}}"
REPOSITORY                              TAG       IMAGE ID       CREATED AT                      SIZE
ghcr.io/home-assistant/home-assistant   stable    8c4dce8bf037   2025-05-23 11:20:44 -0400 EDT   1.94GB
zwavejs/zwave-js-ui                     latest    b9d314fcae79   2025-05-15 06:04:18 -0400 EDT   383MB
```
That said, I noticed HASS image is timestamped is close to when I started seeing this issue.

So trying an older image `docker pull homeassistant/home-assistant:2025.5.2`. But no, that's not it.

Turned out I had a path of HASS config wrong. In `docker-compose.yaml`,
```
version: '3.7'
services:
  home_assistant:
    container_name: home_assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/nnoodle/cws/src/noodle/confrepo/conf/hass/:/config
      #- ${PATH_HASS_CONFIG}:/config
      - /etc/localtime:/etc/localtime:ro
:
```
When the issue was occurring, the "`nnoodle`" was mistakenly wrong.
