### ISSUE TITLE
Address rospy#1384

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#675]
Personal work on https://github.com/ros/ros_comm/issues/1384 is logged in this ticket.

**Comment by 130s** [comment]
Complete code to confirm the issue (enhancing the partial code in https://github.com/ros/ros_comm/issues/1384#issue-319859166):

Term-1:
```
$ docker run -it ros:noetic-ros-base bash
# source /opt/ros/noetic/setup.bash && roscore
```
Term-2:
```
$ docker exec -it adoring_saha bash

# apt update && apt install -y ipython3
# source /opt/ros/noetic/setup.bash && ipython3

import logging
import rospy
LOGGERNAME = "my-logger"
logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(LOGGERNAME)
logger.warning(1)
print(logger)
rospy.init_node("whaterver")
logger.warning(2)
rospy.loginfo(3)
logger = logging.getLogger(LOGGERNAME)
logger.warning(4)
```

Output:
```
WARNING:my-logger:1
<RospyLogger my-logger (WARNING)>
[INFO] [1652475919.130251]: 3
```
What is the class `RospyLogger`??

**Comment by 130s** [comment]
```
$ cd ros_comm && ack -ir RospyLogger .
tools/rosgraph/src/rosgraph/roslogging.py
51:class RospyLogger(logging.getLoggerClass()):
57:        file_name, lineno, func_name = super(RospyLogger, self).findCaller(*args, **kwargs)[:3]
93:logging.setLoggerClass(RospyLogger)

tools/rosgraph/test/test_roslogging_user_logger.py
35:to ensure the custom logger won't be overwritten by RospyLogger defined
80:    logging.setLoggerClass(rosgraph.roslogging.RospyLogger)

tools/rosgraph/CHANGELOG.rst
46:* fix RospyLogger findCaller arguments in Python 3.8 (`#1838 <https://github.com/ros/ros_comm/issues/1838>`_)
91:* make RospyLogger.findCaller compatible with Python 3 (`#1121 <https://github.com/ros/ros_comm/issues/1121>`_)
```
```
$ ack -A 2 -B 2 -ir roslogging clients/rospy/
clients/rospy/src/rospy/impl/init.py
46-
47-import rosgraph
48:import rosgraph.roslogging
49-import rosgraph.xmlrpc
50-
--
107-    return node
108-
109:class RosStreamHandler(rosgraph.roslogging.RosStreamHandler):
110-    def __init__(self, colorize=True, stdout=None, stderr=None):
111-        super(RosStreamHandler, self).__init__(colorize=colorize, stdout=stdout, stderr=stderr)

clients/rospy/src/rospy/core.py
65-import rospkg
66-
67:import rosgraph.roslogging
68-
69-import rospy.exceptions
--
403-        if filename == suffix:
404-            raise rospy.exceptions.ROSException('invalid configure_logging parameter: %s'%node_name)
405:    _log_filename = rosgraph.roslogging.configure_logging('rospy', level, filename=filename)
406-
407-class NullHandler(logging.Handler):
```
So there's something around `rosgraph.roslogging.RosStreamHandler`?

**Comment by 130s** [comment]
Hinted at https://stackoverflow.com/questions/50777664/

**Comment by 130s** [comment]
Got it working by supplying a custom logging config without code change. Not sure what permanent fix I can submit to the upstream though.

Custom logging conf (I guess core is `disable_existing_loggers` to be false):
```
# more ~/py_logging.yaml
disable_existing_loggers: False

formatters:
    my_std:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%Y/%m/%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        formatter: my_std
        level: DEBUG
        stream: ext://sys.stdout
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: my_std
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    __main__:
        level: DEBUG
        handlers: [console]
        propagate: goo
    rosout:
        level: INFO
        propagate: yes
        qualname: rosout

root:
    level: INFO
    handlers: [console, info_file_handler]
```

To verify, supply this config file to this sample code.
ATM, I have been only able to get it work with the conf file set via the environment variable `export ROS_PYTHON_LOG_CONFIG_FILE=~/py_logging.yaml` (i.e. Trying to supply the config file path in Python code like the following results in not resolving the issue).

```
import logging 
import os
import rospy

def load_logging_conf(config_path):
    if os.path.exists(config_path):
        with open(config_path, 'rt') as f:
            config = yaml.safe_load(f.read())
        config.setdefault('version', 1)
        logging.config.dictConfig(config)

def setup_logging(default_path='logging.yaml', default_level=logging.INFO, env_key='LOG_CFG'
):
    """Setup logging configuration

    """
    path = default_path
    value = os.getenv(env_key, None)
    if value:
        path = value
    if os.path.exists(path):
        with open(path, 'rt') as f:
            config = yaml.safe_load(f.read())
        logging.config.dictConfig(config)
    else:
        logging.basicConfig(level=default_level)

def fix_logging(level=logging.WARNING):
    console = logging.StreamHandler()
    console.setLevel(level)
    logging.getLogger('').addHandler(console)
    formatter = logging.Formatter('%(levelname)-8s:%(name)-12s: %(message)s')
    console.setFormatter(formatter)
    logging.getLogger('').addHandler(console)

LOGGERNAME = "my-logger" 

config_path = "~/py_logging.yaml"
load_logging_conf(config_path)

#logging.basicConfig(level=logging.WARN) 
logger = logging.getLogger(LOGGERNAME) 
logger.warning("genlog-1") 
print(logger) 
rospy.loginfo(2) 

rospy.init_node("whaterver") 
logger.warning(3) 
rospy.loginfo(4) 
logger = logging.getLogger(LOGGERNAME) 
logger.warning(5) 
#fix_logging()

#setup_logging(config_path)
#logger = logging.getLogger(LOGGERNAME)

logger.warning("genlog-6")
rospy.loginfo("roslog-7")
```

Result when the issue is resolved:
```
genlog-1
<RospyLogger my-logger (WARNING)>
2022/05/16 21:16:00 - rospy.client - INFO - init_node, name[/whaterver], pid[8344]
2022/05/16 21:16:00 - xmlrpc - INFO - XML-RPC server binding to 0.0.0.0:0
2022/05/16 21:16:00 - xmlrpc - INFO - Started XML-RPC server [http://4a33e0109f61:43839/]
2022/05/16 21:16:00 - rospy.init - INFO - ROS Slave URI: [http://4a33e0109f61:43839/]
2022/05/16 21:16:00 - rospy.impl.masterslave - INFO - _ready: http://4a33e0109f61:43839/
2022/05/16 21:16:00 - rospy.registration - INFO - Registering with master node http://localhost:11311
2022/05/16 21:16:00 - xmlrpc - INFO - xml rpc node: starting XML-RPC server
2022/05/16 21:16:00 - rospy.init - INFO - registered with master
2022/05/16 21:16:00 - rospy.rosout - INFO - initializing /rosout core topic
2022/05/16 21:16:00 - rospy.rosout - INFO - connected to core topic /rosout
2022/05/16 21:16:00 - rospy.simtime - INFO - /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
2022/05/16 21:16:00 - my-logger - WARNING - 3
2022/05/16 21:16:00 - rosout - INFO - 4
2022/05/16 21:16:00 - my-logger - WARNING - 5
2022/05/16 21:16:00 - my-logger - WARNING - genlog-6
2022/05/16 21:16:00 - rosout - INFO - roslog-7

In [2]: 2022/05/16 21:16:00 - rospy.internal - INFO - topic[/rosout] adding connection to [/rosout], count 0
```
Result when the issue remains:
```
genlog-1
<RospyLogger my-logger (WARNING)>
[INFO] [1652735910.049111]: 4
[INFO] [1652735910.053469]: roslog-7
```
