### ISSUE TITLE
robotics: Get joint positions per given set of joints takes considerable amount of work

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#834]
This is a ROS-specific subset of my broader question [robotics.stackexchange.com#24740](https://robotics.stackexchange.com/questions/24740/checking-the-h-w-completed-the-commanded-move) (initiated while struggling with https://github.com/kinu-garage/essay_in_idleness/issues/140 where I thought it'd be a quick development but turned out that the pose-verification is a blocker). What are the ways to know the the hardware moved to the intended positions/pose?

So far I've found/thought of:

- [joint_state_broadcaster (control.ros.org)](https://control.ros.org/master/doc/ros2_controllers/joint_state_broadcaster/doc/userdoc.html) pubs a single topic that aggregates values from all joints, not just a single hardware.
   - This is aggregated so I have to pick the joints of my interest, which may be a very light lift.
- From [good'ol PR2 tutorial](http://wiki.ros.org/pr2_controllers/Tutorials/Getting%20the%20current%20joint%20angles), at bit lower layer solution subscribing to `JointState`.
- [FollowJointTrajectory (docs.ros.org/noetic)](http://docs.ros.org/en/noetic/api/control_msgs/html/action/FollowJointTrajectory.html) feedback returns [trajectory_msgs/JointTrajectoryPoint](http://docs.ros.org/en/noetic/api/trajectory_msgs/html/msg/JointTrajectoryPoint.html), but not in the final result. If a controller's implementation returns the joint values in the feedback, checking the last bit of the feedback may suffice?

**Comment by 130s** [comment]
Example `/joint_states` info.

<details><summary>From ariac2023</summary>

```
# ros2 topic info -v /joint_states                  
Type: sensor_msgs/msg/JointState                                      
                                                                      
Publisher count: 1                                                    
                                                                      
Node name: joint_state_broadcaster                                    
Node namespace: /                                                     
Topic type: sensor_msgs/msg/JointState                                                                                                       
Endpoint type: PUBLISHER                                              
GID: d4.44.10.01.1f.50.8f.4d.91.bc.80.21.00.02.af.03.00.00.00.00.00.00.00.00
QoS profile:                                                          
  Reliability: RELIABLE                                               
  Durability: VOLATILE                                                
  Lifespan: 9223372036854775807 nanoseconds
  Deadline: 9223372036854775807 nanoseconds
  Liveliness: AUTOMATIC                                               
  Liveliness lease duration: 9223372036854775807 nanoseconds
                                                                      
Subscription count: 4                                                 

# ros2 topic echo /joint_states                  
header:                 
  stamp:                
    sec: 717         
    nanosec: 67000000
  frame_id: ''          
name: 
- agv1_joint             
- agv2_tray_joint       
- agv1_tray_joint     
- agv3_joint           
- agv3_tray_joint      
- agv4_joint           
- ceiling_elbow_joint    
- ceiling_gripper_joint
- agv2_joint
- ceiling_shoulder_pan_joint
- ceiling_shoulder_lift_joint
- floor_elbow_joint
- linear_actuator_joint
- gantry_y_axis_joint
- gantry_x_axis_joint
- ceiling_wrist_1_joint
- floor_gripper_joint
- gantry_tray_joint
- agv4_tray_joint
- floor_wrist_3_joint
- floor_wrist_2_joint
- gantry_rotation_joint
- floor_shoulder_pan_joint
- ceiling_wrist_2_joint
- floor_wrist_1_joint
- floor_shoulder_lift_joint
- ceiling_wrist_3_joint
position:
- 1.1719472839704264e-05
- 0.0009543241121239276
- 0.0008584220706682189
- -1.7048140679586195e-11
- -9.989194982296112e-08
- -1.7048140679586195e-11
- 4.524248762294292e-06
- -0.00019334115035896104
- 2.01304216467403e-05
- -4.25296035100331e-06
- -3.661932696630288e-06
- 1.5709950724624138
- 1.7832267216836455e-05
- -8.445047105036165e-08
- -3.2624509139207856e-07
- -5.638025332110885e-05
- 0.0009970844970350612
- -8.834130849066923e-08
- -9.985371285381461e-08
- 0.011961401420911066
- -1.5710496856260319
- -6.672750545000383e-06
- 2.5008235202683693e-05
- 3.2806371068616613e-06
- -1.5709720820637108
- -1.5709109207583882
- 5.620826521646194e-05
velocity:
- 2.1232234454650366e-07
- .nan
- .nan
- -3.467215648404449e-13
- .nan
- -3.467198301159374e-13
- 0.0005787741999563106
- .nan
- 2.5320388734774867e-07
- -0.00425297404426925
- -0.0004067539623502806
- 0.019955260217822998
- -6.164165715331471e-06
- -8.445365514080109e-05
- -0.0003262474701778876
- -0.0563802531912086
- .nan
- 1.8917562676946942e-10
- .nan
- -1.7318542001881266e-06
- -5.390709860544688e-07
- 0.001885078778462771
- 5.950513237072689e-07
- 0.0032806375061668665
- -0.029151357074390677
- -2.2822369428049617e-05
- 0.056208265241004036
effort:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- 0.0
- .nan
- .nan
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- .nan
- 0.0
- .nan
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```
</details>
